const express=require('express');const http=require('http');const {Server}=require('socket.io');const path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname,'public')));
const rooms=new Map(),users=new Map();const MAX=2;const walls=[{x:0,z:0,w:2,d:40},{x:0,z:40,w:42,d:2},{x:40,z:0,w:2,d:42},{x:0,z:0,w:42,d:2},{x:12,z:13,w:5,d:4},{x:27,z:24,w:5,d:4},{x:19,z:8,w:4,d:6},{x:19,z:29,w:4,d:5}];
const code=()=>{let c;do{c=Math.random().toString(36).slice(2,6).toUpperCase()}while(rooms.has(c));return c};const safe=(v)=>String(v||'Pilot').replace(/[<>]/g,'').slice(0,18);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function collision(x,z){return walls.some(w=>x>w.x-.48&&x<w.x+w.w+.48&&z>w.z-.48&&z<w.z+w.d+.48)}
function state(r){return {code:r.code,started:r.started,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,x:p.x,z:p.z,yaw:p.yaw,hp:p.hp,kills:p.kills,dead:p.dead})),score:r.score,events:r.events.slice(-8)}}
function publish(r){io.to(r.code).emit('state',state(r))}
function leave(s){let u=users.get(s.id);if(!u)return;const r=rooms.get(u.code);users.delete(s.id);if(!r)return;r.players.delete(s.id);s.leave(r.code);if(!r.players.size)rooms.delete(r.code);else{r.started=false;publish(r)}}
function join(s,r,name){leave(s);if(r.players.size>=MAX)return s.emit('notice','Lobby full');const i=r.players.size;const p={id:s.id,name:safe(name),x:i?35:7,z:i?34:7,yaw:i?Math.PI:0,hp:100,kills:0,dead:false,lastShot:0};r.players.set(s.id,p);users.set(s.id,{code:r.code});s.join(r.code);r.started=r.players.size===MAX;s.emit('joined',{code:r.code,id:s.id});publish(r)}
io.on('connection',s=>{s.on('create',({name}={})=>{const c=code();const r={code:c,players:new Map(),started:false,score:[0,0],events:[]};rooms.set(c,r);join(s,r,name)});s.on('join',({code:c,name}={})=>{const r=rooms.get(String(c||'').toUpperCase());if(!r)return s.emit('notice','Lobby not found');join(s,r,name)});s.on('move',data=>{const r=rooms.get(users.get(s.id)?.code),p=r?.players.get(s.id);if(!p||!r.started||p.dead)return;const dx=clamp(Number(data?.dx)||0,-1,1),dz=clamp(Number(data?.dz)||0,-1,1);const mag=Math.hypot(dx,dz);const scale=mag>1?1/mag:1;const nx=p.x+dx*scale*.22,nz=p.z+dz*scale*.22;if(!collision(nx,p.z))p.x=nx;if(!collision(p.x,nz))p.z=nz;if(Number.isFinite(data?.yaw))p.yaw=clamp(data.yaw,-100000,100000)});s.on('fire',()=>{const r=rooms.get(users.get(s.id)?.code),p=r?.players.get(s.id);if(!p||!r.started||p.dead||Date.now()-p.lastShot<220)return;p.lastShot=Date.now();const enemy=[...r.players.values()].find(q=>q.id!==p.id&&!q.dead);let hit=false;if(enemy){const dx=enemy.x-p.x,dz=enemy.z-p.z,range=Math.hypot(dx,dz),dir=Math.atan2(dx,dz),err=Math.atan2(Math.sin(dir-p.yaw),Math.cos(dir-p.yaw));if(range<26&&Math.abs(err)<.16){let blocked=false;for(let t=.3;t<range;t+=.22)if(collision(p.x+Math.sin(dir)*t,p.z+Math.cos(dir)*t)){blocked=true;break}if(!blocked){enemy.hp=Math.max(0,enemy.hp-25);hit=true;if(enemy.hp===0){enemy.dead=true;p.kills++;r.events.push(p.name+' eliminated '+enemy.name);setTimeout(()=>{if(!r.players.has(enemy.id))return;enemy.hp=100;enemy.dead=false;enemy.x=enemy.x<20?7:35;enemy.z=enemy.z<20?7:34;publish(r)},2500)}}}}io.to(r.code).emit('shot',{id:p.id,x:p.x,z:p.z,yaw:p.yaw,hit});publish(r)});s.on('chat',msg=>{const r=rooms.get(users.get(s.id)?.code),p=r?.players.get(s.id);if(!r||!p)return;io.to(r.code).emit('chat',{name:p.name,text:String(msg||'').trim().slice(0,120)})});s.on('leave',()=>leave(s));s.on('disconnect',()=>leave(s))});setInterval(()=>{for(const r of rooms.values())if(r.players.size)publish(r)},80);server.listen(process.env.PORT||3000,()=>console.log('FREAKYROBOTGAME http://localhost:'+(process.env.PORT||3000)));
